### PR TITLE
fixed new chroot bug

### PR DESCRIPTION
**Pull request by fengmk2**
fix bug which https://github.com/dannycoates/zkjs/commit/776e127eec560fed3ed454fb3155662f2c95cf4f commit include.

That cause path wrong.

### CODE REVIEW

**Comment by fengmk2** [comment]
@dannycoates I thank zkjs should add auto test on travis-ci.org.

I pub a test zk server on `'api.yongwo.de:2181'`, you can use it.

**Comment by dannycoates** [comment]
Yes, it needs some automated testing. I don't have much time for this project right now. Here, have some commit access :)

**Comment by fengmk2** [comment]
ok, I will add the tests code after my holiday.

On Monday, April 29, 2013, Danny Coates wrote:

> Yes, it needs some automated testing. I don't have much time for this
> project right now. Here, have some commit access :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/dannycoates/zkjs/pull/9#issuecomment-17140776
> .

## 

@fengmk2 https://twitter.com/fengmk2
@Python发烧友 http://weibo.com/imk2/profile
http://fengmk2.github.com

---

_记得当时年纪小/
你爱谈天，我爱笑/
有一回并肩坐在桃树下/
风在林梢鸟儿在叫/
我们不知怎样睡着了/
梦里花落知多少_

**Comment by bobrik** [comment]
:+1: for this patch! :)

**Comment by richtera** [comment]
the code we're currently using (I sent the original chroot fix) looks as follows:

``` javascript
    Session.prototype._chroot = function (path) {
        if (path.charAt(0) !== '/') {
            path = (this.root + '/' + path).replace(/\/\//, '/');
        }
        if (path.length > 1 && path[path.length - 1] === '/') {
            path = path.substring(0, path.length - 1);
        }
        return path
    }
```

I can create a pull request. What was the "That cause path wrong." exactly about?

**Pull request merged**
